language: php

services:
  - mysql

php:
  - 5.6
  - 7.0

addons:
    code_climate:
        repo_token: a4a2b434edd8850ccf5354c3dc1202b1c824cd442fe7c4c5a2d0d82edef1cae0

sudo: false

env:
    - APP_ENV=local DB_DATABASE=followers_test DB_TEST_USERNAME=travis DB_TEST_PASSWORD= CACHE_DRIVER=array SESSION_DRIVER=array QUEUE_DRIVER=sync

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --dev --prefer-source --no-interaction

before_script:
  - mysql -e 'create database followers_test;'
  - cp src/database/migrations/create_followers_table.php vendor/laravel/laravel/database/migrations/2016_09_07_053825_create_followers_table.php
  - yes | cp tests/config/.env.travis .env
  - yes | cp tests/config/followers.php vendor/laravel/laravel/config/followers.php
  - yes | cp tests/Stub_User.php vendor/laravel/laravel/app/User.php
  - cd vendor/laravel/laravel
  - composer update --dev --prefer-source --no-interaction
  - php artisan migrate
  - cd -

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
